### ISSUE TITLE
logo contribution

### ISSUE THREAD

**Issue by reallinfo** [sophiabrandt/feedbacky#1]
Hi @sophiabrandt I designed a original and minimalist logo to better represent feedbacky. What do you think? I will wait for 'FEEDBACK'Y! :)

![feedbacky](https://user-images.githubusercontent.com/36298335/56050681-2ec86880-5d55-11e9-9f26-8a68d3a60775.png)

![feedbacky2](https://user-images.githubusercontent.com/36298335/56050690-32f48600-5d55-11e9-8d79-f61fc56ca6cb.jpg)

![feedback3](https://user-images.githubusercontent.com/36298335/56050885-b1e9be80-5d55-11e9-9fd1-07967497bc39.jpg)

**Comment by sophiabrandt** [comment]
@reallinfo That logo looks sweet!
This is a toy project but I'm thankful for your help. Can you provide svg or png files?
What is the licence of the logo?

**Comment by reallinfo** [comment]
Sure :) I sent a pr and i updated the readme file. You can contact me if you need another logo.  The logo is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)

**Comment by sophiabrandt** [comment]
Thank you. I will change the app in the following days and give you credit in the Readme. Thanks!

**Comment by reallinfo** [comment]
Thanks! Feel free to write me if you need help about logo.

**Comment by sophiabrandt** [comment]
Merged with master https://github.com/sophiabrandt/feedbacky/pull/2
